import os

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
cpppath = [cwd]

group = DefineGroup('print', src, CPPPATH=cpppath)

for script in FindChildScripts(cwd):
    SConscript(script)

Return('group')
