import os

from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c')
cpppath = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup('app', src, CPPPATH=cpppath)

for script in FindChildScripts(cwd):
    SConscript(script)

Return('group')
