import os
from building import *

src = Glob('src/*.c')

cwd = GetCurrentDir()
path = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup('app', src, CPPPATH=path)

for script in FindChildScripts(cwd):
    SConscript(script)

Return('group')
