import os

from building import *

Import('target_chip', 'target_mcu')

cwd = GetCurrentDir()
src = [
    File(os.path.join(target_mcu, 'cmsis', 'Source', 'Templates', 'system_stm32f4xx.c')),
    File(os.path.join(target_mcu, 'cmsis', 'Source', 'Templates', 'gcc', f'startup_{target_chip}.s')),
]
cpppath = [
    os.path.join(cwd, target_mcu, 'cmsis', 'Include'),
    os.path.join(cwd, target_mcu, 'hal', 'Inc'),
    os.path.join(cwd, 'cmsis_core'),
]
group = DefineGroup('target', src, CPPPATH=cpppath)

Return('group')
